apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-sql 
  labels:
    app : chatbot-sql
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec: 
    containers:
    - name: chatbot-mysql
      image: mysql
      ports :
      - containerPort: 4322
    env: 
      - name: MYSQL_ROOT_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: mysql-secret
            key: username
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: database